title: "我的个人学术主页"
theme: jekyll-theme-cayman
description: "展示我的学术成果和研究项目"
url: "https://yourusername.github.io"
baseurl: ""
author: "Jie Han"
markdown: kramdown

# 菜单导航（可选）
navigation:
  - name: Home
    link: /
  - name: Publications
    link: /publications
  - name: Projects
    link: /projects
  - name: Contact
    link: /contact
